"""create articles table

Revision ID: 25af490e7457
Revises: 6dee72fd4622
Create Date: 2026-09-23 23:05:47.490666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '25af490e7457'
down_revision: Union[str, Sequence[str], None] = '6dee72fd4622'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('ingestion_run_id', sa.UUID(), nullable=True),
    sa.Column('story_id', sa.UUID(), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('canonical_url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('community_score', sa.Integer(), nullable=True),
    sa.Column('community_comments', sa.Integer(), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=True),
    sa.Column('raw_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('processing_state', sa.Enum('DISCOVERED', 'NORMALIZED', 'DEDUPLICATED', 'CLUSTERED', 'FAILED', 'RETRYABLE', name='article_processing_state'), server_default='DISCOVERED', nullable=False),
    sa.Column('processing_attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'canonical_url', name='uq_articles_source_canonical_url')
    )
    op.create_index('idx_articles_processing_state', 'articles', ['processing_state'], unique=False)
    op.create_index('idx_articles_source_published', 'articles', ['source_id', 'published_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    op.drop_index(
        'idx_articles_source_published',
        table_name='articles',
    )

    op.drop_index(
        'idx_articles_processing_state',
        table_name='articles',
    )

    op.drop_table('articles')

    sa.Enum(
        name='article_processing_state'
    ).drop(
        op.get_bind(),
        checkfirst=True,
    )
