"""create sources table

Revision ID: 6dee72fd4622
Revises: 
Create Date: 2026-09-20 22:15:37.821942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6dee72fd4622'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('source_type', sa.Enum('RSS', 'PUBLIC_API', 'GITHUB_RELEASE', 'MANUAL', name='source_type'), nullable=False),
    sa.Column('source_category', sa.Enum('OFFICIAL', 'NEWS', 'COMMUNITY', 'RESEARCH', 'GOVERNMENT', 'RELEASE', name='source_category'), nullable=False),
    sa.Column('default_region', sa.Enum('GLOBAL', 'INDIA', 'TAMIL_NADU', name='region_code'), nullable=True),
    sa.Column('base_url', sa.Text(), nullable=True),
    sa.Column('endpoint_url', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('fetch_interval_minutes', sa.Integer(), server_default='60', nullable=False),
    sa.Column('reputation_weight', sa.Numeric(precision=5, scale=4), server_default='0.5000', nullable=False),
    sa.Column('http_etag', sa.Text(), nullable=True),
    sa.Column('http_last_modified', sa.Text(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('fetch_interval_minutes > 0', name='ck_sources_fetch_interval_positive'),
    sa.CheckConstraint('reputation_weight >= 0 AND reputation_weight <= 1', name='ck_sources_reputation_weight_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('idx_sources_enabled', 'sources', ['enabled'], unique=False)
    op.create_index('idx_sources_type_enabled', 'sources', ['source_type', 'enabled'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    op.drop_index(
        'idx_sources_type_enabled',
        table_name='sources'
    )

    op.drop_index(
        'idx_sources_enabled',
        table_name='sources'
    )

    op.drop_table('sources')

    sa.Enum(name='region_code').drop(
        op.get_bind(),
        checkfirst=True,
    )

    sa.Enum(name='source_category').drop(
        op.get_bind(),
        checkfirst=True,
    )

    sa.Enum(name='source_type').drop(
        op.get_bind(),
        checkfirst=True,
    )